### ISSUE TITLE
Hello, after testing found that if using this plug-in for K sampler batch generation, only a single image appears? Could this be rectified in the future?

### ISSUE THREAD

**Issue by azhaozz** [lquesada/ComfyUI-Inpaint-CropAndStitch#1] opened 2024-05-13 08:26 UTC

**Comment by lquesada** [comment] 2024-05-13 13:45
Hi,

In order to make sure I understand this correctly and I address your use case, could you:
1) Provide a minimalistic, as simple as possible, workflow with these nodes where batch doesn't work?
2) Provide a minimalistic, as simple as possible, workflow with other nodes where batch works?
3) Let me know any alternatives/additional context that I should know?

I may be able to fix this.

Thanks,
Luis.

**Comment by merc4derp** [comment] 2024-05-14 19:19
Seconding this problem. The stitcher needs to be able to handle batches.

The whole idea with this node is to speedup the workflow so you can try more things.

In my workflow, I take the cropped image from the inpaint crop node, vae encode to latent space and sending the latent through a repeat latent batch node, repeating it 4 times.

The sampler correctly creates 4 images which I can preview.

But when I pass them through the stitcher, only the first image remains.

**Comment by lquesada** [comment] 2024-05-14 19:37
yes, I was independently looking into this right now and just managed to reproduce it with the following setup:

![test](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/4499933/b4e51267-93b6-4321-8621-b3369648fb5f)

It's not the stitcher, it's both nodes.

I need to figure out how some nodes deal with batches. Thanks for your example, that's very useful.

**Comment by lquesada** [comment] 2024-05-14 20:51
good news, I'm testing this, it works.

**Comment by lquesada** [comment] 2024-05-14 20:54
ok, just pushed the support for batch - please give it a go and let me know :)

**Comment by lquesada** [comment] 2024-05-14 21:32
Ok, there's something missing in stitch yet for some use cases (batch repeat latent). On it now.

**Comment by lquesada** [comment] 2024-05-14 22:08
I think I won't support batch repeat latent, because if latent is multiplied, stitch will not match the amount of latents. You should use repeat image before crop. I'll indeed have to do some changes to how batching works for animateDiff - return a batched image, a batched mask, and a single stitch that I'll batch, then the stitch node will use that info to regenerate properly - this avoids images being outputted as an array.

That would be incompatible with fixing it for repeat batch latent.

**Comment by merc4derp** [comment] 2024-05-14 22:46
Sure, that can work. Probably a bit of extra overhead but nothing major. 

So, doing a repeat image batch on the masked initial image and then the stitcher will unbatch it. Sounds good. Cheers.

**Comment by lquesada** [comment] 2024-05-15 07:18
This is now proper batch processing. Just committed.

As stated, it won't work with repeat_batch_latent but it would work with repeat image batch. You'll have to do a similar operation for the mask though.

**Closed by lquesada** 2024-05-15 07:18 UTC
